version: '3.9'

services:
  server:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:12.22
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_DB: ${PG_NAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ./:/data/db
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql